### PR TITLE
Add Spryker Framework for PHP7.1+

### PR DESCRIPTION
**Pull request by dereuromark**
Nov 2017
https://academy.spryker.com/what_s_new/releases/release_notes_august_1_2017.html#announcements

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hey @dereuromark, glad to hear that.

I'm not sure I understand this: 

> With the end of October we stop supporting PHP 5.6. Please make sure your infrastructure is running on 7.1+ before that.

There is PHP 7.0 version missing, either from top or from the bottom.

**Comment by dereuromark** [comment]
7.0 is skipped as your document suggests.
So from 5.x directly to 7.1+ (which you promote on your website).
How does that not clarify in that announcement?
Should it add a more explicit "We skip 7.0 as outlined in [gophp71.org](gophp71.org) etc?

**Comment by TomasVotruba** [comment]
> 7.0 is skipped as your document suggests.

I don't see any info about 7.0. Only about 5.6

> With the end of October we stop supporting PHP 5.6.

From this I conclude PHP 5.6 is dropped and anyhting above is not. So PHP 7.0 is supported.

---

I'd expect something like this:

**With the end of October we stop supporting PHP 5.6 and PHP 7.0.**

**Comment by dereuromark** [comment]
OK :) This can be fixed up.

**Comment by dereuromark** [comment]
Fixed up in the document, also added a backlink to your site :)

**Comment by TomasVotruba** [comment]
Great! Let's merge it than.

> ...also added a backlink to your site :)

Thanks a lot mate :+1:

**Comment by TomasVotruba** [comment]
cc @petrheinz

**Comment by TomasVotruba** [comment]
cc @petrheinz @shopsys

**Pull request merged**
