### PR TITLE
Adding WordPress, based on scientific guesstimate.

### PR DESCRIPTION
**Pull request by ozh**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Are you really sure? :dancer:  ;)

**Comment by ozh** [comment]
Sadly, I'm pretty sure, but feel free to close the PR :)

(A quick comment while I'm here: if you want this to take off (nice initiative by the way, although I'm not sure why you're targeting specifically 7.1 and not 7+ or 7.2) I think it would be much much more convenient to submit PR against a simple file format such as YML or JSON instead of plain old HTML tables...)

**Comment by TomasVotruba** [comment]
@ozh To your awesome comment: would you be able to send PR with that that would work on Github Pages?

**Comment by TomasVotruba** [comment]
Closing now.

Yaml was added by @salathe - thank you man!

**Pull request closed without merging**
