### PR TITLE
Add phpMyAdmin 5.0

### PR DESCRIPTION
**Pull request by MauricioFauth**
https://github.com/phpmyadmin/phpmyadmin/milestone/237

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hey Maurício,

thanks for the PR. In the references issue, I see bumping to PHP 5.6+, not 7.1+.

**Comment by MauricioFauth** [comment]
Hi, @TomasVotruba.
The issue for this has not yet been created, but you can see in the description of the milestone.
You can also check this in this meeting log:
https://github.com/phpmyadmin/phpmyadmin/wiki/2017-12_Meeting#meeting-3

**Comment by TomasVotruba** [comment]
That's better link. Could use that one please?

**Comment by MauricioFauth** [comment]
@TomasVotruba done.

**Comment by TomasVotruba** [comment]
Thank you! 

Btw, just a Christmas idea - have you ever thought about joining forces with https://github.com/vrana/adminer?
You're pretty much doing similar job and working together can push that even further.

**Comment by MauricioFauth** [comment]
Honestly, I don't know if vrana ever had any contact with phpMyAdmin.
But I can say from my own experience that phpMyAdmin is a project that is very receptive to new contributors and new ideas.

**Pull request merged**
